version: 1
update_configs:
  - package_manager: "elixir:hex"
    directory: "/apps/diet"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/apps/diet_web/assets/"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
